// <auto-generated />
using System;
using EVDataMarketplace.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVDataMarketplace.API.Migrations
{
    [DbContext(typeof(EVDataMarketplaceDbContext))]
    [Migration("20251103064253_RemoveOldPurchaseModels")]
    partial class RemoveOldPurchaseModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EVDataMarketplace.API.Models.APIKey", b =>
                {
                    b.Property<int>("KeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("key_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeyId"));

                    b.Property<int>("ApiPurchaseId")
                        .HasColumnType("int")
                        .HasColumnName("api_purchase_id");

                    b.Property<int>("ConsumerId")
                        .HasColumnType("int")
                        .HasColumnName("consumer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("KeyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("key_name");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("key_value");

                    b.Property<DateTime?>("LastRequestDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_request_date");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_used_at");

                    b.Property<int>("RequestsToday")
                        .HasColumnType("int")
                        .HasColumnName("requests_today");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("revoked_reason");

                    b.HasKey("KeyId");

                    b.HasIndex("ApiPurchaseId");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("KeyValue")
                        .IsUnique();

                    b.ToTable("APIKey");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.APIPackage", b =>
                {
                    b.Property<int>("ApiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("api_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApiId"));

                    b.Property<int?>("ApiCallsPurchased")
                        .HasColumnType("int")
                        .HasColumnName("api_calls_purchased");

                    b.Property<int>("ApiCallsUsed")
                        .HasColumnType("int")
                        .HasColumnName("api_calls_used");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("api_key");

                    b.Property<int?>("ConsumerId")
                        .HasColumnType("int")
                        .HasColumnName("consumer_id");

                    b.Property<int?>("DatasetId")
                        .HasColumnType("int")
                        .HasColumnName("dataset_id");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<decimal?>("PricePerCall")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_per_call");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalPaid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_paid");

                    b.HasKey("ApiId");

                    b.HasIndex("ApiKey")
                        .IsUnique()
                        .HasFilter("[api_key] IS NOT NULL");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("DatasetId");

                    b.ToTable("APIPackage");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.APIPackagePurchase", b =>
                {
                    b.Property<int>("ApiPurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("api_purchase_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApiPurchaseId"));

                    b.Property<int>("ApiCallsPurchased")
                        .HasColumnType("int")
                        .HasColumnName("api_calls_purchased");

                    b.Property<int>("ApiCallsUsed")
                        .HasColumnType("int")
                        .HasColumnName("api_calls_used");

                    b.Property<int>("ConsumerId")
                        .HasColumnType("int")
                        .HasColumnName("consumer_id");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<decimal>("PricePerCall")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("price_per_call");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_paid");

                    b.HasKey("ApiPurchaseId");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("APIPackagePurchase");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.DataConsumer", b =>
                {
                    b.Property<int>("ConsumerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("consumer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumerId"));

                    b.Property<string>("BillingEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("billing_email");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contact_number");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("contact_person");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("organization_name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ConsumerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DataConsumer");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.DataPackagePurchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("purchase_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<int>("ConsumerId")
                        .HasColumnType("int")
                        .HasColumnName("consumer_id");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int")
                        .HasColumnName("download_count");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<DateTime?>("LastDownloadDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_download_date");

                    b.Property<int>("MaxDownload")
                        .HasColumnType("int")
                        .HasColumnName("max_download");

                    b.Property<decimal>("PricePerRow")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("price_per_row");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<int>("RowCount")
                        .HasColumnType("int")
                        .HasColumnName("row_count");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_price");

                    b.HasKey("PurchaseId");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("DataPackagePurchase");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.DataProvider", b =>
                {
                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("provider_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProviderId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyWebsite")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("company_website");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ProviderId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DataProvider");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.Dataset", b =>
                {
                    b.Property<int>("DatasetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dataset_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatasetId"));

                    b.Property<string>("Category")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("category");

                    b.Property<string>("DataFormat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("data_format");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_updated");

                    b.Property<string>("ModerationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("moderation_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("PortId")
                        .HasColumnType("int")
                        .HasColumnName("port_id");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("provider_id");

                    b.Property<int>("RowCount")
                        .HasColumnType("int")
                        .HasColumnName("row_count");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("upload_date");

                    b.Property<string>("Visibility")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("visibility");

                    b.HasKey("DatasetId");

                    b.HasIndex("Category");

                    b.HasIndex("ModerationStatus");

                    b.HasIndex("ProviderId");

                    b.HasIndex("Status");

                    b.ToTable("Dataset");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.DatasetModeration", b =>
                {
                    b.Property<int>("ModerationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("moderation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModerationId"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comments");

                    b.Property<int?>("DatasetId")
                        .HasColumnType("int")
                        .HasColumnName("dataset_id");

                    b.Property<string>("ModerationStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("moderation_status");

                    b.Property<int?>("ModeratorUserId")
                        .HasColumnType("int")
                        .HasColumnName("moderator_user_id");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("review_date");

                    b.HasKey("ModerationId");

                    b.HasIndex("DatasetId");

                    b.HasIndex("ModeratorUserId");

                    b.ToTable("DatasetModeration");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.DatasetRecord", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecordId"));

                    b.Property<decimal?>("BatteryCapacityKwh")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("battery_capacity_kwh");

                    b.Property<decimal?>("ChargingCost")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("charging_cost");

                    b.Property<DateTime>("ChargingTimestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("charging_timestamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Current")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("current");

                    b.Property<string>("DataSource")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("data_source");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<decimal?>("DurationMinutes")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("duration_minutes");

                    b.Property<decimal>("EnergyKwh")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("energy_kwh");

                    b.Property<decimal?>("PowerKw")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("power_kw");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.Property<decimal?>("SocEnd")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("soc_end");

                    b.Property<decimal?>("SocStart")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("soc_start");

                    b.Property<string>("StationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("station_address");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("station_id");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("station_name");

                    b.Property<string>("StationOperator")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("station_operator");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("vehicle_type");

                    b.Property<decimal?>("Voltage")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("voltage");

                    b.HasKey("RecordId");

                    b.HasIndex("ChargingTimestamp");

                    b.HasIndex("DatasetId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId", "DistrictId");

                    b.ToTable("DatasetRecords");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type");

                    b.HasKey("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("District");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.OneTimePurchase", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("otp_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<int?>("ConsumerId")
                        .HasColumnType("int")
                        .HasColumnName("consumer_id");

                    b.Property<int?>("DatasetId")
                        .HasColumnType("int")
                        .HasColumnName("dataset_id");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int")
                        .HasColumnName("download_count");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("LicenseType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("license_type");

                    b.Property<int>("MaxDownload")
                        .HasColumnType("int")
                        .HasColumnName("max_download");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.HasKey("OtpId");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("DatasetId");

                    b.ToTable("OneTimePurchase");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("ConsumerId")
                        .HasColumnType("int")
                        .HasColumnName("consumer_id");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("payment_type");

                    b.Property<string>("PayosOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("payos_order_id");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int")
                        .HasColumnName("reference_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("transaction_ref");

                    b.HasKey("PaymentId");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("PaymentDate");

                    b.HasIndex("Status");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.Payout", b =>
                {
                    b.Property<int>("PayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payout_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayoutId"));

                    b.Property<string>("BankAccount")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("bank_account");

                    b.Property<string>("MonthYear")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("month_year");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("payment_method");

                    b.Property<DateTime?>("PayoutDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payout_date");

                    b.Property<string>("PayoutStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payout_status");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("provider_id");

                    b.Property<decimal?>("TotalDue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_due");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("transaction_ref");

                    b.HasKey("PayoutId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Payout");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.HasKey("ProvinceId");

                    b.ToTable("Province");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.RevenueShare", b =>
                {
                    b.Property<int>("ShareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("share_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShareId"));

                    b.Property<decimal?>("AdminShare")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("admin_share");

                    b.Property<DateTime>("CalculatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("calculated_date");

                    b.Property<int?>("DatasetId")
                        .HasColumnType("int")
                        .HasColumnName("dataset_id");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    b.Property<string>("PayoutStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payout_status");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("provider_id");

                    b.Property<decimal?>("ProviderShare")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("provider_share");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("ShareId");

                    b.HasIndex("DatasetId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ProviderId");

                    b.ToTable("RevenueShare");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.Subscription", b =>
                {
                    b.Property<int>("SubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sub_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubId"));

                    b.Property<int?>("ConsumerId")
                        .HasColumnType("int")
                        .HasColumnName("consumer_id");

                    b.Property<int?>("DatasetId")
                        .HasColumnType("int")
                        .HasColumnName("dataset_id");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.Property<string>("RenewalCycle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("renewal_cycle");

                    b.Property<string>("RenewalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("renewal_status");

                    b.Property<int>("RequestCount")
                        .HasColumnType("int")
                        .HasColumnName("request_count");

                    b.Property<DateTime?>("SubEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("sub_end");

                    b.Property<DateTime?>("SubStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("sub_start");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.HasKey("SubId");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("DatasetId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.SubscriptionPackagePurchase", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subscription_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit")
                        .HasColumnName("auto_renew");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("billing_cycle");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancelled_at");

                    b.Property<int>("ConsumerId")
                        .HasColumnType("int")
                        .HasColumnName("consumer_id");

                    b.Property<int>("DashboardAccessCount")
                        .HasColumnType("int")
                        .HasColumnName("dashboard_access_count");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<DateTime?>("LastAccessDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_access_date");

                    b.Property<decimal>("MonthlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("monthly_price");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_paid");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("SubscriptionPackagePurchase");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.SystemPricing", b =>
                {
                    b.Property<int>("PricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pricing_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PricingId"));

                    b.Property<decimal>("AdminCommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("admin_commission_percent");

                    b.Property<decimal?>("ApiPricePerCall")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("api_price_per_call");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("package_type");

                    b.Property<decimal>("PricePerRow")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("price_per_row");

                    b.Property<decimal>("ProviderCommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("provider_commission_percent");

                    b.Property<decimal?>("SubscriptionMonthlyBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("subscription_monthly_base");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PricingId");

                    b.ToTable("SystemPricing");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("User");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.APIKey", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.APIPackagePurchase", "APIPackagePurchase")
                        .WithMany("APIKeys")
                        .HasForeignKey("ApiPurchaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EVDataMarketplace.API.Models.DataConsumer", "DataConsumer")
                        .WithMany("APIKeys")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("APIPackagePurchase");

                    b.Navigation("DataConsumer");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.APIPackage", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.DataConsumer", "DataConsumer")
                        .WithMany("APIPackages")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EVDataMarketplace.API.Models.Dataset", "Dataset")
                        .WithMany("APIPackages")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DataConsumer");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.APIPackagePurchase", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.DataConsumer", "DataConsumer")
                        .WithMany("APIPackagePurchases")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EVDataMarketplace.API.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EVDataMarketplace.API.Models.Province", "Province")
                        .WithMany("APIPackagePurchases")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DataConsumer");

                    b.Navigation("District");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.DataConsumer", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.User", "User")
                        .WithOne("DataConsumer")
                        .HasForeignKey("EVDataMarketplace.API.Models.DataConsumer", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.DataPackagePurchase", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.DataConsumer", "DataConsumer")
                        .WithMany("DataPackagePurchases")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EVDataMarketplace.API.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EVDataMarketplace.API.Models.Province", "Province")
                        .WithMany("DataPackagePurchases")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataConsumer");

                    b.Navigation("District");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.DataProvider", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.Province", "Province")
                        .WithMany("DataProviders")
                        .HasForeignKey("ProvinceId");

                    b.HasOne("EVDataMarketplace.API.Models.User", "User")
                        .WithOne("DataProvider")
                        .HasForeignKey("EVDataMarketplace.API.Models.DataProvider", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.Dataset", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.DataProvider", "DataProvider")
                        .WithMany("Datasets")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataProvider");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.DatasetModeration", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.Dataset", "Dataset")
                        .WithMany("DatasetModerations")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EVDataMarketplace.API.Models.User", "Moderator")
                        .WithMany("DatasetModerations")
                        .HasForeignKey("ModeratorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dataset");

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.DatasetRecord", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.Dataset", "Dataset")
                        .WithMany("DatasetRecords")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVDataMarketplace.API.Models.District", "District")
                        .WithMany("DatasetRecords")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EVDataMarketplace.API.Models.Province", "Province")
                        .WithMany("DatasetRecords")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("District");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.District", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.OneTimePurchase", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.DataConsumer", "DataConsumer")
                        .WithMany("OneTimePurchases")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EVDataMarketplace.API.Models.Dataset", "Dataset")
                        .WithMany("OneTimePurchases")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DataConsumer");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.Payment", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.DataConsumer", "DataConsumer")
                        .WithMany("Payments")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DataConsumer");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.Payout", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.DataProvider", "DataProvider")
                        .WithMany("Payouts")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DataProvider");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.RevenueShare", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.Dataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId");

                    b.HasOne("EVDataMarketplace.API.Models.Payment", "Payment")
                        .WithMany("RevenueShares")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EVDataMarketplace.API.Models.DataProvider", "DataProvider")
                        .WithMany("RevenueShares")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DataProvider");

                    b.Navigation("Dataset");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.Subscription", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.DataConsumer", "DataConsumer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EVDataMarketplace.API.Models.Dataset", "Dataset")
                        .WithMany("Subscriptions")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EVDataMarketplace.API.Models.Province", "Province")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DataConsumer");

                    b.Navigation("Dataset");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.SubscriptionPackagePurchase", b =>
                {
                    b.HasOne("EVDataMarketplace.API.Models.DataConsumer", "DataConsumer")
                        .WithMany("SubscriptionPackagePurchases")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EVDataMarketplace.API.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EVDataMarketplace.API.Models.Province", "Province")
                        .WithMany("SubscriptionPackagePurchases")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataConsumer");

                    b.Navigation("District");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.APIPackagePurchase", b =>
                {
                    b.Navigation("APIKeys");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.DataConsumer", b =>
                {
                    b.Navigation("APIKeys");

                    b.Navigation("APIPackagePurchases");

                    b.Navigation("APIPackages");

                    b.Navigation("DataPackagePurchases");

                    b.Navigation("OneTimePurchases");

                    b.Navigation("Payments");

                    b.Navigation("SubscriptionPackagePurchases");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.DataProvider", b =>
                {
                    b.Navigation("Datasets");

                    b.Navigation("Payouts");

                    b.Navigation("RevenueShares");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.Dataset", b =>
                {
                    b.Navigation("APIPackages");

                    b.Navigation("DatasetModerations");

                    b.Navigation("DatasetRecords");

                    b.Navigation("OneTimePurchases");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.District", b =>
                {
                    b.Navigation("DatasetRecords");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.Payment", b =>
                {
                    b.Navigation("RevenueShares");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.Province", b =>
                {
                    b.Navigation("APIPackagePurchases");

                    b.Navigation("DataPackagePurchases");

                    b.Navigation("DataProviders");

                    b.Navigation("DatasetRecords");

                    b.Navigation("Districts");

                    b.Navigation("SubscriptionPackagePurchases");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("EVDataMarketplace.API.Models.User", b =>
                {
                    b.Navigation("DataConsumer");

                    b.Navigation("DataProvider");

                    b.Navigation("DatasetModerations");
                });
#pragma warning restore 612, 618
        }
    }
}
